### ISSUE TITLE
joystick becomes very hard to move & automatically moves to the left of the screen [BUG]

### ISSUE THREAD

**Issue by Aayush022** [yoannmoinet/nipplejs#125]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots, Codepen or JSFiddle**
If applicable, add screenshots, codepen or jsfiddle to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yoannmoinet** [comment]
Please follow the issue template.

**Comment by jharris1993** [comment]
This is not necessarily a bug in nipple.js. . .

You need to look at the code **_using_** nipple.js and see how it reacts to, and uses, the "force" returned by nipple.

For example, using the Remote Camera Robot script on the GoPiGo robot, the "determined speed" is calculated by _**adding**_ "force" to the other parts of the equation for "determined speed", where these other constants are non-zero values.

Viz.:  (written in Python-3)
```
# earlier in the program, constants used in determining the speed are created.
MAX_FORCE = 5.0
MIN_SPEED = 100
MAX_SPEED = 500 
#
# . . . . more program code . . . .
#
# the section in question, note particularly the equation for "determined speed"
@app.route("/robot", methods = ["POST"])
def robot_commands():

    # get the query
    args = request.args
    state = args['state']
    angle_degrees = int(float(args['angle_degrees']))
    angle_dir = args['angle_dir']
    force = float(args['force'])

    # calculate "determined_speed" from values received
    determined_speed = (MIN_SPEED + force) * (MAX_SPEED - MIN_SPEED) / (MAX_FORCE)
```
Note that "determined_speed" will **_never be zero_** because the three constants are not zero, particularly "MIN_SPEED" - so the "determined_speed" will **_never be zero_** either. This can cause the device using nipple.js to suddenly lurch forward, (for example), and make a hard skew to the left.

The solution in this case is to add a small addition to the code, right after the "determined_speed" is calculated.

Viz.:
```
    determined_speed = (MIN_SPEED + force) * (MAX_SPEED - MIN_SPEED) / (MAX_FORCE)

    # add case where force = 0
    if force == 0:
        determined_speed = 0
```
Here, we check for the special case where force is zero _i.e._ the nipple is not being moved, and if that's the case, set the determined speed to zero.

You can make the action of your device less "touchy", by multiplying the denominator by a constant value, in my case, I used "2"

Viz:
```
    # note the additional factor multiplied by MAX_FORCE in the denominator
    determined_speed = (MIN_SPEED + force) * (MAX_SPEED - MIN_SPEED) / (2 * MAX_FORCE)

    # add case where force = 0
    if force == 0:
        determined_speed = 0
```
I don't know if your case is similar to this, but you may want to look at how the returned values from nipple.js are being used.  You may find something similar.

I hope this helps.

Jim "JR"
