### ISSUE TITLE
Add an option `follow` to the joystick

### ISSUE THREAD

**Issue by yoannmoinet** [yoannmoinet/nipplejs#13]
This will make the joystick follow the finger/cursor when going farther than the back circle.

This way, it will allow to have a revert movement way faster and shorter than with a fixed joystick.

**Comment by emepetres** [comment]
Hi @yoannmoinet , is this implemented?

**Comment by yoannmoinet** [comment]
No it's not.

I don't think this is needed or required by anyone after all.
Never saw any joystick implement this feature.

Do you need it? What would be your use-case?

**Comment by emepetres** [comment]
Thanks @yoannmoinet , what I'm trying to achieve, that I think would improve the user experience, is the following:

Lets say the user takes the joystick and goes up surpassing the threshold with its finger because it wants go up very fast. Then, it want to decrease the velocity a little bit, and moves the finger slowly down but, as the finger is already out of the threshold, it is not going to do anything until it reaches the threshold.

So to avoid this what I would want is that the joystick would be responsive to the finger/mouse even if it is outside the threshold, because in a screen the user gets out of it many times wihtout noticing. One way to achieve this is by doing the joystick to follow your finger/mouse when you surpass the threshold.

**Comment by matthewrobb** [comment]
Working on this myself currently. A good example of this type of feature can be found in the mobile game Brawl Stars. I saw a WIP implementation [here](https://github.com/yoannmoinet/nipplejs/compare/features/follow), any interest in this picking back up?

**Comment by yoannmoinet** [comment]
It is being implemented in https://github.com/yoannmoinet/nipplejs/pull/160
And it looks promising, very close to be shipped.
