### ISSUE TITLE
Multiple static joysticks

### ISSUE THREAD

**Issue by ThumbGen** [yoannmoinet/nipplejs#20]
Hi

Amazing lib! 

I am trying to setup 2 static joysticks in 2 different zones.
Something like: http://jsfiddle.net/k2xcey8j/4/

It seems to work until I try to move both joysticks in the same time (multitouch): one of them gets stuck and the other one continues to work well :(  No chance to 'revive' the dead one, it remains dead until the next refresh.

I reproduce the behavior on Windows Phone and Android (real devices).I don't have a touchscreen display to try on PC.

Is this a bug or the configuration is not supported?

Thanks in advance!

Best regards
TG

**Comment by yoannmoinet** [comment]
Thanks for the feedback :smile: 

I am aware of the condition, you can catch up the discussion on [this thread](https://github.com/yoannmoinet/nipplejs/issues/16#issuecomment-155224047)

The configuration should be supported, and in theory it was supposed to work.
But there was a major issue in architecture which provoked a big performance hit.

That's why I'm refactoring some stuff to avoid having this performance issue.
I just forgot to create a issue for it, so it's perfect that you did.

For some ETA, I'll try to achieve it this week end.
I'm a little loaded at the moment. That's why it takes so much time :disappointed:

**Comment by ThumbGen** [comment]
Wow, you are fast :)  No hurry at all! Thank you!

**Comment by yoannmoinet** [comment]
As an update, the refactor is almost done, and it's working amazingly well :smiley:.
You can follow along [here](https://github.com/yoannmoinet/nipplejs/tree/features/refactor)

I also did a [streaming :movie_camera:](https://www.livecoding.tv/yoannm/), if you're interested in that sort of things :wink:.

It's very closed to be done, I still have a small bug in `semi` mode that I need to tackle.
And I also have to update the doc, there are some small changes.

**Comment by Derrick56007** [comment]
:+1:

**Comment by yoannmoinet** [comment]
This is fixed in #22.

**Comment by ThumbGen** [comment]
Hi

Tried the new code but I think it still has some problems.
I cannot use 2 different joysticks by using multitouch at all. 
Also funny is that it influences other controls (nouislider) too :)

I have 2 joysticks (different zones, both static) and a slider. 
If I use one control at a time it works perfectly.
If I keep one joystick pressed I cannot use the other one OR by moving the other one the first one moves too (same happens with the slider too).

Maybe you can try to test the multitouch behavior on a touch-device, it is pretty interesting (I tried on WinPhone, Windows tablet and Android tablet and the behavior is the same)

Thanks!

**Comment by yoannmoinet** [comment]
Thanks for reporting this.
Do you have a demo page for this?
So I can replicate it.

**Comment by ThumbGen** [comment]
See  http://jsfiddle.net/k2xcey8j/10/

1. Tap one of the joysticks... after ~1-2 seconds the tap is lost and the control is back to untapped state (even if the finger is still pressing it)

2. With 1 finger tap the slider and while keeping pressed move _vertically_ with some other finger any of the joysticks: the slider moves too! (not sure if this is a slider issue or a joystick issue)

3. Not covered in the sample but sometimes I feel the events (start end) are mixed up: I press one joystick and keep pressed; then I press the second one and release: the "end" event of the first joystick is triggered

In "singletouch" mode the control works perfectly!

**Comment by yoannmoinet** [comment]
I've modified a few things, can you tell me if it's working a little better now ?
http://jsfiddle.net/NeekGerd/p7jwu0qq/

In fact, your zones were 0px of height. 
So I think it might have induced some touch weirdness.

If there is still a problem I'll see this later.

**Comment by ThumbGen** [comment]
I see no change in behavior :(

**Comment by yoannmoinet** [comment]
Hey !
I've tried to reproduce your problem : 
![2015-12-10_15-53-41](https://cloud.githubusercontent.com/assets/597828/11728220/a000b57c-9f56-11e5-9356-1303a63e876f.gif)
This is a screen capture of me debugging my Nexus 5. So I'm on multitouch in chrome, I've tried several stuff and gimmicks, I couldn't get a wrong behavior. Is it what you're seeing too?

For the slider, I was able to reproduce your `2.` : 
![2015-12-10_15-59-09](https://cloud.githubusercontent.com/assets/597828/11728283/fbbd6d6a-9f56-11e5-8023-ae34d8f199aa.gif)
In fact, I would say that the developer of the slider is listening for **every** `touchmove` events on the `body`, and not only the one that activated it (like I do :sunglasses:). That's why he wrongfully intercepts my event.

I'd suggest to log an issue on his project for this, he's the one not playing nice with others :laughing:.

I have no Windows touch based device though, so I can't test it on Edge. I'll try it on Firefox though, to see if I can reproduce your problem there.

**Comment by ThumbGen** [comment]
Hi!

It seems the slider has indeed an incorrect implementation! I will file a bug there ASAP.

Thanks a lot for looking into it and sorry for wasting your time with the bug report.

The first issue is very difficult to reproduce, I feel it might be related to the pressure applied. I simply tap a joystick (real device, no emulator) and after 1-2 seconds it switches to "released" state (thus triggering the 'end' event). It is not something critical, just don't spend any more time with it.

Thanks again for this amazing library!

**Comment by yoannmoinet** [comment]
Are you using it on a iOS device with 3D touch?

**Comment by ThumbGen** [comment]
No, no IOS device at all :) Just a plain old Windows Phone and an even older Android tablet :)
