### ISSUE TITLE
Joystick is off on mobile version

### ISSUE THREAD

**Issue by mavkci** [yoannmoinet/nipplejs#69]
This is what happens when I tried to open my site in mobile browser.
https://imgur.com/a/dBvtZ

**Comment by yoannmoinet** [comment]
I'll have a look.

**Comment by lazerwalker** [comment]
@mavkci maybe you've figured out a solution or workaround by now, but in my own experience I've found issues like this are often caused by CSS. 

Because the joystick element is positioned via `position: absolute`, its immediate parent should have `position: relative` or else you'll likely see unexpected behavior.

**Comment by yoannmoinet** [comment]
Couldn't reproduce the issue and missing details.
Closing until more is added.
