### ISSUE TITLE
Rename this library?

### ISSUE THREAD

**Issue by lazerwalker** [yoannmoinet/nipplejs#80]
Hi!

First of all, thanks so much for making this. It's easily the best JS virtual joystick library I'm found — everything about it, from the API to the docs to the actual UI it provides, are a joy (no pun intended :P) to work with.

That said, I wonder if you'd consider changing the name? From the "nipple" terminology, to the peach flesh-colored joystick in the logo, a lot about the library's branding makes me a bit uncomfortable. I'm incredibly hesitant to discuss it or recommend it in a professional setting or discuss it with colleagues, which is incredibly unfortunate for a library that I'd like to both contribute to and suggest that my colleagues use.

I'm happy to help with the nuts-and-bolts gruntwork of handling a rename (documentation updates, renaming variables, etc), but obviously as the maintainer of the project this is ultimately a decision for you to make.

**Comment by TheCodeCrafter** [comment]
How about JoyJS? I mean, there's so many options using just the word Joystick 😆

**Comment by lazerwalker** [comment]
I like JoyJS! Some other ideas off the top of my head:

- StickJS
- AnalogJS
- MoveJS

I think I personally like JoyJS the best out of all of these, but I figure brainstorming can't hurt.

**Comment by dcholth** [comment]
Please do not rename this library.  Reading bug reports like Issue #82 brings a small amount of glee to my day.

**Comment by ollwenjones** [comment]
I didn't even make the connection to a human nipple, since I was just playing with the blue demo, until a coworker immediately responded "nswf!" to my slack. There are a few other non-fleshy uses of the word, after all, e.g. bicycle spoke nipples. Short of a rename I think adjusting the branding colors would help. The name might be partly responsible for the libs fame, but it's also likely some would pass it over because of the name + branding.

joystick.js seems to be taken by a jQuery plugin 😞

**Comment by TheCodeCrafter** [comment]
Ah. Yay. Looks like my idea held out 👍

**Comment by yoannmoinet** [comment]
@lazerwalker JoyJS is good, but it's already taken on NPM https://www.npmjs.com/package/joyjs
Even if we can go with the capitalized one https://www.npmjs.com/package/JoyJS, I don't think it's a good idea since it can be really confusing.

So we have to go with something else.

What about Nipply?
So can still keep the previous tongue-in-cheek name without being nsfw with it.

**Comment by ezelohar** [comment]
@yoannmoinet don't give up to the pressure of few people. 
What is there to be uncomfortable, I don't get it.

**Comment by jeeftor** [comment]
I believe the name is rather descriptive.

**Comment by TheCodeCrafter** [comment]
I don't know. I like the current name where it is, to be honest. I don't see it as necessary to change the name, but I also see where @lazerwalker was coming from.

**Comment by lazerwalker** [comment]
So far, the strongest opposition to this is "eh, I don't see what there is to be offended about".

If this change is made, a few things have to happen:
* Some stuff has to change in this repo (which, as mentioned, I'm happy to do).
* Some other bureaucracy has to happen outside this repo (e.g. updating npm)
* Individual consumers of this library will need to probably update their package.json file. It wouldn't surprise me if npm's repo will even auto-redirect for you so that you don't have to for current projects, only if you add it to a new project in the future. 

That doesn't seem like a lot of work. As a result, people who are _sitting in this thread actively telling you they feel uncomfortable because of the name_ will continue to use, recommend, and contribute to this library, helping it grow and become better. 

Some of you might not get why this is a problem. Cool. But is this a hill you're willing to die on?

**Comment by lazerwalker** [comment]
For someone who allegedly doesn't think at all about the name, you sure do seem to care a lot about it. I agree it would be great if we could focus on the project itself — which is why changing the name quickly and moving on is far preferable to sitting here arguing all day.

I'm trying to figure out what objections you have to a name change other than not understanding why it matters, and perhaps feeling a sense that giving me what I want is harmful to the project. Are there tangible reasons to keep it as-is that I'm missing?

The numbers you cite feel like an argument in bad faith. There are roughly equal numbers for/against in this thread; both of those numbers are higher than the number of contributors who have actively had PRs accepted into this project. But also, the nature of exclusion is such that people who felt uncomfortable by the name are exceedingly unlikely to return to the project to even see this thread. I hesitate to even bring this up, because devolving into an argument about numbers feels secondary to actually sussing out why this change is even remotely a bad thing.

**Comment by ezelohar** [comment]
@lazerwalker if you have so much time to argue with a random person over a script name,  you probably have time to develop it yourself and give it any name you want.

_For someone who allegedly doesn't think at all about the name, you sure do seem to care a lot about it._

You wanted to say what? When did I say I don't think about the name? I like the name and would like to continue using NipplesJS not StickJS or MoveJS or AnalogJS or whatever LazarWantsToBeJS. 

_I agree it would be great if we could focus on the project itself — which is why changing the name quickly and moving on is far preferable to sitting here arguing all day._

Again you are pushing your own way. You say "Let's do it my way and get over it". The project lives anyway, no matter what you say or forces about the name.

_I'm trying to figure out what objections you have to a name change other than not understanding why it matters, and perhaps feeling a sense that giving me what I want is harmful to the project. Are there tangible reasons to keep it as-is that I'm missing?_

I am trying to figure out what objections you have to this name and want to change it other than your personal attitude? This is not a commercial project and it brings some joy in the daily life of the developers. So are there tangible reasons to change it except the attitude of few people who do have some personal issues with the nipples? 
Here https://external-preview.redd.it/_hwA4udE2MWGz_Lke1iiEHah-hq_5jH3elJ-vc4fjOU.jpg?auto=webp&s=0df3b5e2d8506bcf7ab6b69a08df6358ddcd4843 
Check this image.

_The numbers you cite feel like an argument in bad faith. There are roughly equal numbers for/against in this thread; both of those numbers are higher than the number of contributors who have actively had PRs accepted into this project. But also, the nature of exclusion is such that people who felt uncomfortable by the name are exceedingly unlikely to return to the project to even see this thread. I hesitate to even bring this up because devolving into an argument about numbers feels secondary to actually sussing out why this change is even remotely a bad thing._

I didn't know that the main reason for using a script is a name? I always thought that we use something because it works and solves the problem we had? I never knew before that there are people to feel so uncomfortable by the name "Nipple" so they will avoid using a library this good? 
There are other libraries with offensive names. .e.g imagine puppeteer. Why not go and ask them to change the name? 

Do you have a belief that only your point of view is right and that everyone else is wrong? 

Your behaviour is same like going to visit your friends and when you are leaving their house, you say to them "Hey, it was great staying at your place, but please can you change the colours of your walls and the chairs in the kitchen? That colour was making me uncomfortable and those chairs also. I will come again to visit in two years so please make sure to do all of this."
In my point of view, you are offending your host who gave you this useful library.

And if nipples really make you uncomfortable, maybe you should visit a professional? Today you can't run away from nipples, they are everywhere and you will just be more and more uncomfortable. 

But, even with all I say, I do understand your belief that more neutral name has less chance not to be accepted, but in my personal opinion, here in this script and discussion, it is just irrelevant. If something is good, you can call it shit it will be still used.  
Read this and change your life https://waitbutwhy.com/2014/06/taming-mammoth-let-peoples-opinions-run-life.html

All best.

**Comment by yoannmoinet** [comment]
This is getting out of hand.
I'm closing the issue right now.

There will be no change of name, it's asking too much work and too many side-effects that we can't easily predict.

If you really are offended by the name of the library, feel free to fork it and publish it under a name you like.

But I just want to add that I really don't accept seeing stuff like this posted [on Twitter](https://twitter.com/lazerwalker/status/1054658757228195840).
![image](https://user-images.githubusercontent.com/597828/47359732-c1a11800-d6cd-11e8-99c0-a83d20a448e4.png)

This is insulting and disrespectful to everyone having a say in the discussion here. 
People are allowed to disagree without being insulted for it.

I'm really sorry we couldn't manage to find an acceptable solution for everyone while keeping the discussion civilised. 

This is a final decision, and NippleJS will remain NippleJS for the time being.

**Comment by lazerwalker** [comment]
I'm sorry for any pain that was caused with that tweet. I hope you can understand my frustration in having people in this thread tell me that my opinion is invalid, but expressing that publicly was a mistake. I was very careful to keep the discussion within this thread civilized, something I wish I could say of others in this thread.

I understand your frustration, even as I disagree with your decision. In the future, I hope you can realize that maintaining an open-source community relies on active fostering of inclusivity, and decisions that appear "neutral" can merely end up discouraging diversity and inclusion.

**Comment by ezelohar** [comment]
@lazerwalker I am so sorry for hurting your feelings by not agreeing with you. My bad, I didn't know you were soo delicate flower.

**Comment by lazerwalker** [comment]
(@yoannmoinet, I may recommend locking this thread to prevent future replies)
